# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=50000']
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: no-commit-to-branch
        args: [-b, staging, -b, release/.*, -b, main]
    -   id: detect-private-key
-   repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.0
    hooks:
    -   id: absolufy-imports
-   repo: https://github.com/hadolint/hadolint
    rev: v2.6.0
    hooks:
      - id: hadolint-docker
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black
# -   repo: https://github.com/pycqa/isort
#     rev: 5.9.2
#     hooks:
#       - id: isort
#         args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    -   id: flake8
        args: [
            "--max-line-length", "120"
        ]
-   repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
